# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-08-21 15:32
from __future__ import unicode_literals

import datetime

from django.db import migrations


def agregar_eventos_desencadenadores(apps, schema_editor):

    eventos_desencadenadores = apps.get_model('Notificaciones', 'EventoDesencadenador')

    eventos_desencadenadores.objects.create(id=1, nombre="Bienvenido a Eva",
                                            descripcion="Bienvenido a Eva",
                                            ruta="/",
                                            fecha_creacion=datetime.datetime.today(), estado=True)

    eventos_desencadenadores.objects.create(id=2, nombre="Creacion de Contratos",
                                            descripcion="Creacion de Contratos",
                                            ruta="/proyectos/contratos",
                                            fecha_creacion=datetime.datetime.today(), estado=True)

    eventos_desencadenadores.objects.create(id=3, nombre="Creacion de Tercero",
                                            descripcion="Creacion de Tercero",
                                            ruta="/administracion/terceros",
                                            fecha_creacion=datetime.datetime.today(), estado=True)

    eventos_desencadenadores.objects.create(id=4, nombre="Creacion de Empresas",
                                            descripcion="Creacion de Empresas",
                                            ruta="/administracion/empresas",
                                            fecha_creacion=datetime.datetime.today(), estado=True)

    eventos_desencadenadores.objects.create(id=5, nombre="Creacion Entidades Cafe",
                                            descripcion="Creacion Entidades Cafe",
                                            ruta="/talento-humano/entidades-index/0",
                                            fecha_creacion=datetime.datetime.today(), estado=True)

    eventos_desencadenadores.objects.create(id=6, nombre="Creacion de Colaboradores",
                                            descripcion="Creacion de Colaboradores",
                                            ruta="/talento-humano/colaboradores-index/0",
                                            fecha_creacion=datetime.datetime.today(), estado=True)

    eventos_desencadenadores.objects.create(id=8, nombre="Cadenas de Aprobación",
                                            descripcion="Cadenas de Aprobación",
                                            ruta="/sgi/aprobacion_documentos",
                                            fecha_creacion=datetime.datetime.today(), estado=True)

    eventos_desencadenadores.objects.create(id=9, nombre="Solicitudes de Aprobación",
                                            descripcion="Solicitudes de Aprobación",
                                            ruta="/sgi/solicitudes_aprobacion/detalle",
                                            fecha_creacion=datetime.datetime.today(),
                                            estado=True, modal=True)


def textos_eventos_desencadenadores(apps, schema_editor):

    textos = apps.get_model('Notificaciones', 'TextoNotificacionDelSistema')

    textos.objects.create(titulo="Bienvenido a EVA",
                          mensaje="Bienvenido a EVA",
                          evento_desencadenador_id=1)

    textos.objects.create(titulo="Creacion de Contratos",
                          mensaje="Creacion de Contratos",
                          evento_desencadenador_id=2)

    textos.objects.create(titulo="Creacion de Tercero",
                          mensaje="Creacion de Tercero",
                          evento_desencadenador_id=3)

    textos.objects.create(titulo="Creacion de Empresas",
                          mensaje="Creacion de Empresas",
                          evento_desencadenador_id=4)

    textos.objects.create(titulo="Creacion Entidades Cafe",
                          mensaje="Creacion Entidades Cafe",
                          evento_desencadenador_id=5)

    textos.objects.create(titulo="Creacion de Colaboradores",
                          mensaje="Creacion de Colaboradores",
                          evento_desencadenador_id=6)


def tipos_de_notificaciones(apps, schema_editor):

    tipo_notificacion = apps.get_model('Notificaciones', 'TipoNotificacion')

    tipo_notificacion.objects.create(id=1,
                                     nombre="Evento del Sistema",
                                     descripcion="Tipo de notificacion que se genera con eventos del sistema",
                                     estado=True)

    tipo_notificacion.objects.create(id=2,
                                     nombre="Obligatoria",
                                     descripcion="Tipo de notificacion que crea el administrador y que la "
                                                 "establece de tipo obligatoria",
                                     estado=True)

    tipo_notificacion.objects.create(id=3,
                                     nombre="Informativa",
                                     descripcion="Tipo de notificacion informativa",
                                     estado=True)


class Migration(migrations.Migration):

    dependencies = [
        ('Notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(agregar_eventos_desencadenadores),
        migrations.RunPython(textos_eventos_desencadenadores),
        migrations.RunPython(tipos_de_notificaciones),
    ]
